server:
  port: 8080

spring:
  application:
    name: eduplatform-backend
  datasource:
    url: jdbc:h2:mem:eduplatform;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: "schimba-aceasta-cheie-in-productie-este-doar-pt-mvp-eduplatform-2026-very-long-secret"
    expiration-ms: 86400000
    cookie-name: "edu_token"
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://localhost:4173"

logging:
  level:
    org.springframework.security: INFO
    ro.eduplatform: INFO
